server:
  port: 2702

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: pass
    realmImportFile: yggdrasil-realm.json
