-- /* ---------------------------------------------------------------------- */
-- /* (Re)create schemes                                                     */
-- /* ---------------------------------------------------------------------- */
CREATE SCHEMA IF NOT EXISTS DS_USER;
CREATE SCHEMA IF NOT EXISTS DS_CUSTOMER;
CREATE SCHEMA IF NOT EXISTS DS_CONTRACT;
CREATE SCHEMA IF NOT EXISTS DS_TARIFF;
CREATE SCHEMA IF NOT EXISTS DS_OPTION;
-- /* ---------------------------------------------------------------------- */
-- /* Add tables                                                             */
-- /* ---------------------------------------------------------------------- */
CREATE TABLE DS_USER.T_USER (
  ID VARCHAR(36) PRIMARY KEY,
  EMAIL VARCHAR(254) NOT NULL,
  PASSWORD VARCHAR(36) NOT NULL,
  ROLE VARCHAR(10) NOT NULL,
  CUSTOMER_ID VARCHAR(36),
  DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE DS_CUSTOMER.T_CUSTOMER (
  ID UUID PRIMARY KEY,
  NAME  VARCHAR(50) NOT NULL,
  LAST_NAME  VARCHAR(50) NOT NULL,
  BIRTHDAY  TIMESTAMP,
  PASSPORT_NUM VARCHAR(12) NOT NULL,
  EMAIL VARCHAR(254) NOT NULL,
  ADDRESS VARCHAR(200) NOT NULL,
  DELETED BOOLEAN DEFAULT FALSE
  );

CREATE TABLE DS_CONTRACT.T_CONTRACT (
  ID UUID PRIMARY KEY,
  NUMBER  VARCHAR(20) NOT NULL,
  TARIFF_ID  VARCHAR(36) NOT NULL,
  CUSTOMER_ID  VARCHAR(36) NOT NULL,
  OPTION_LIST_ID  VARCHAR(36) NOT NULL,
  TOTAL_PRICE DECIMAL,
  DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE DS_CONTRACT.T_OPTION_LISTS (
  ID UUID PRIMARY KEY,
  LIST_ID  VARCHAR(36) NOT NULL,
  OPTION_ID  VARCHAR(36) NOT NULL,
  STATUS CHARACTER(20) NOT NULL,
  DELETED BOOLEAN DEFAULT FALSE
  );

CREATE TABLE DS_TARIFF.T_TARIFF (
  ID UUID PRIMARY KEY,
  NAME  VARCHAR(50) NOT NULL,
  DESCRIPTION  VARCHAR(200),
  OPTION_LIST_ID  VARCHAR(36) NOT NULL,
  PRICE DECIMAL,
  DELETED BOOLEAN DEFAULT FALSE
  );

CREATE TABLE DS_TARIFF.T_OPTION_LISTS (
  ID UUID PRIMARY KEY,
  LIST_ID  VARCHAR(36) NOT NULL,
  OPTION_ID  VARCHAR(36) NOT NULL,
  DELETED BOOLEAN DEFAULT FALSE
  );

CREATE TABLE DS_OPTION.T_OPTION (
  ID UUID PRIMARY KEY,
  NAME  VARCHAR(50) NOT NULL,
  DESCRIPTION  VARCHAR(200),
  PRICE DECIMAL,
  CONNECTION_COST DECIMAL,
  DELETED BOOLEAN DEFAULT FALSE
  );


-- ALTER TABLE T_USER
-- ADD CONSTRAINT T_USER_UNIQUE_EMAIL UNIQUE (EMAIL);
--
-- COMMENT ON TABLE T_USER IS 'Table with contents with information about user';
-- COMMENT ON COLUMN T_USER.ID IS 'Primary key';
-- COMMENT ON COLUMN T_USER.EMAIL IS 'It is login to enter the system';
-- COMMENT ON COLUMN T_USER.CUSTOMER_ID IS 'Reference to a customer stored in ds-customer service';